----AIRCRAFTSHOP----
    ['luxor'] = {
	['name'] = 'Luxor',
	['brand'] = 'Luxor',
	['model'] = 'luxor',
	['price'] = 15000000,
	['category'] = 'privatejet',
	['hash'] = `luxor`,
	['shop'] = 'LAVS',
},
    ['luxor2'] = {
	['name'] = 'Luxor Super Delux',
	['brand'] = 'Luxor',
	['model'] = 'luxor2',
	['price'] = 20000000,
	['category'] = 'privatejet',
	['hash'] = `luxor2`,
	['shop'] = 'LAVS',
},    
    ['nimbus'] = {
	['name'] = 'Nimbus',
	['brand'] = 'Nimbus',
	['model'] = 'nimbus',
	['price'] = 25000000,
	['category'] = 'privatejet',
	['hash'] = `nimbus`,
	['shop'] = 'LAVS',
},    
	['shamal'] = {
	['name'] = 'Shamal Super Jet',
	['brand'] = 'Shamal',
	['model'] = 'shamal',
	['price'] = 30000000,
	['category'] = 'privatejet',
	['hash'] = `shamal`,
	['shop'] = 'LAVS',
},    
	['havok'] = {
	['name'] = 'Havok',
	['brand'] = 'Havok',
	['model'] = 'havok',
	['price'] = 300000,
	['category'] = 'helikopter',
	['hash'] = `havok`,
	['shop'] = 'LAVS',
},    
	['swift2'] = {
	['name'] = 'Luxury Swift Delux',
	['brand'] = 'Swift',
	['model'] = 'swift2',
	['price'] = 300000,
	['category'] = 'helikopter',
	['hash'] = `swift2`,
	['shop'] = 'LAVS',
},    
	['supervolito'] = {
	['name'] = 'Super Volito',
	['brand'] = 'Volito',
	['model'] = 'supervolito',
	['price'] = 300000,
	['category'] = 'helikopter',
	['hash'] = `supervolito`,
	['shop'] = 'LAVS',
},    
	['volatus'] = {
	['name'] = 'Volatus Delux',
	['brand'] = 'Volatus',
	['model'] = 'volatus',
	['price'] = 300000,
	['category'] = 'helikopter',
	['hash'] = `volatus`,
	['shop'] = 'LAVS',
},
----AIRCRAFTSHOP----
